<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../OverlayDisk.Cloud.Baidu/OverlayDisk.Cloud.Baidu.csproj" /><ProjectReference Include="../OverlayDisk.Cloud.Sync/OverlayDisk.Cloud.Sync.csproj" /></ItemGroup>
</Project>
